name: RunnerInfo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Context:
    name: Context
    runs-on: ubuntu-latest
    
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - name: Print all env vars
        run: printenv
  
  Perfecto:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Run code
        run: |
          docker run --rm "ghcr.io/essentialkaos/perfecto:micro" --version
          wget https://raw.githubusercontent.com/essentialkaos/perfecto/master/perfecto-container
          wget https://raw.githubusercontent.com/essentialkaos/kaos-repo/develop/specs/etcd.spec
          chmod +x perfecto-container
          ./perfecto-container -f github etcd.spec
