name: RunnerInfo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Context:
    name: Context
    runs-on: ubuntu-latest
    
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
  
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Print system info
        run: cat /etc/os-release

      - name: List users
        run: getent passwd

      - name: List groups
        run: getent group

      - name: List /etc
        run: ls -lah /etc/

      - name: List environment variables
        run: printenv | sort -h

  macOS:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Print system info
        run: sw_vers

      - name: List users
        run: dscl . list /Users

      - name: List groups
        run: dscl . list /Groups

      - name: List /etc
        run: ls -lah /etc/
        
      - name: List environment variables
        run: printenv | sort -h
