name: RunnerInfo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Context:
    name: Context
    runs-on: ubuntu-latest
    
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
  
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Exec
        run: |
          wget -O perfecto-container https://raw.githubusercontent.com/essentialkaos/perfecto/master/perfecto-container
          wget https://raw.githubusercontent.com/essentialkaos/kaos-repo/develop/specs/etcd.spec
          chmod +x perfecto-container
          export IMAGE="ghcr.io/essentialkaos/perfecto:micro"
          export ENGINE=""
          ./perfecto-container -f github etcd.spec
